In [1]:
import pandas as pd

In [2]:
# Read all sheets in your File
Filepath=r"C:\Users\derek\Downloads\Ethiopia All business 2022-11-07.xlsx_updated.xlsx"
sheets = pd.ExcelFile(Filepath).sheet_names
data = pd.read_excel(Filepath)
print(sheets)
data=data.head(0)

for sheet in sheets:
    df = pd.read_excel(Filepath, sheet_name=sheet)
    df["Region"]=sheet
    data=data.append(df)
dataframe=data.append(data)

['Amara', 'oromiya', 'Addis ababa', 'federal', 'debub', 'sidama', 'Southwest ethiopia', 'somale', 'gambela', 'harar', 'dire dawa', 'afar', 'EIA Commetion', 'benshangul']

C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(df)
C:\Users\derek\AppData\Local\Temp\ipykernel_30516\3748448387.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe=data.append(data)

In [3]:
#Mapping Data
mapping_data=pd.read_csv(r"C:\Users\derek\Downloads\translation_table.csv")
mapping_data

,translation_id,translation_id_source,word_se,word_en,entity_type,lang,added_date,added_by
0,1,1000001.0,አዲስ አበባ,Addis Ababa,Region,Amharic,2021-11-03 14:12:48,Africa 118
1,2,1000002.0,ኦሮሚያ,Oromia,Region,Amharic,2021-11-03 14:12:48,Africa 118
2,3,1000003.0,አማራ,Amahra,Region,Amharic,2021-11-03 14:12:48,Africa 118
3,4,1000004.0,ደ/ብ/ብ/ክ/መንግስት,SNNPR government,Region,Amharic,2021-11-03 14:12:48,Africa 118
4,5,1000005.0,ትግራይ,Tigray,Region,Amharic,2021-11-03 14:12:48,Africa 118
...,...,...,...,...,...,...,...,...
74261,74262,1074262.0,ኮስታሪካዊ,Costa Rican,Citizenship,Amharic,2021-11-03 14:13:24,Africa 118
74262,74263,1074263.0,ባንግላዴሻዊ,Bangladeshi,Citizenship,Amharic,2021-11-03 14:13:24,Africa 118
74263,74264,1074264.0,አልጄርያዊ,Algerian,Citizenship,Amharic,2021-11-03 14:13:24,Africa 118
74264,74265,1074265.0,ቤላሩሳዊ,Belarusian,Citizenship,Amharic,2021-11-03 14:13:24,Africa 118
74265,74266,1074266.0,ጅቡቲያዊ,Djibouti,Citizenship,Amharic,2021-11-03 14:13:24,Africa 118

In [4]:
category=pd.read_csv(r"C:\Users\derek\OneDrive\Documents\addis_ababa_data_categories.csv")
category=category[["category_id","category_description"]]
category

     category_id                               category_description
0          33112   Manufacture of textile articles,textile ascceris
1          71113         (71113)Land transport and related services
2          62411  (62411)Retail trade of cotton,textile fibers,y...
3          65312  Import trade leather,leather products and rela...
4          61912  Wholesale of vehicles spare parts and artifici...
..           ...                                                ...
515        66652  Export trade in Animal Medical supplies and eq...
516        21221               Digging of chemicals and fertilizers
517        11124                               silkworm development
518        21231                Extraction and evaporation of salt
519        86516                     Consultancy service metrology

[520 rows x 2 columns]

In [5]:
dataframe=dataframe[["Tin",'TradeNameAmh', 'EngilshName','ManagerFName',
       'ManagerMName', 'ManagerLName', 'MangerPhone','BussinessAmharicRegions', 'BussinessAmharicZones',
       'BussinessAmharicWoredas', 'BussinessAmharickebeles', 'HousNum','BussinessTelephone', 'Region'
          ,'Subgroupcode']]
dataframe

,Tin,TradeNameAmh,EngilshName,ManagerFName,ManagerMName,ManagerLName,MangerPhone,BussinessAmharicRegions,BussinessAmharicZones,BussinessAmharicWoredas,BussinessAmharickebeles,HousNum,BussinessTelephone,Region,Subgroupcode
0,0061843031,መለሰ ሞገስ አለምነህ,MELESE MOGES ALEMINEH,መለሰ,ሞገስ,አለምነህ,0945141608,አማራ,ሰሜን ወሎ,ላስታ,DEBRE LOZA,አዲስ/New,0945141608,Amara,11121
1,0004291057,መለሰ ተፈራ ሁነኛው,MELSE TEFRA HUNEGNAW,መለሰ,ተፈራ,ሁነኛው,913477502,አማራ,ምዕራብ ጎጃም,ወንበርማ,KEBELE 01,አዲስ,0913477502,Amara,62221
2,0058448215,እየሩሳሌም ጌትነት ታደሰ,EYERUSALAME GETENATE TADAS,እየሩሳሌም,ጌትነት,ታደሰ,0912737194,አማራ,ሰሜን ሸዋ,ደብረ ብርሀን(ከተማ),KEBELE 06,0207/2,0912737194,Amara,62412
3,0044302998,ቀለም አያሌው ተሻለ,KELEM AYALEW TESHALE,ቀለም,አያሌው,ተሻለ,0913572423,አማራ,ምስራቅ ጎጃም,አነድድ,KEBELE 01,አዲስ/New,0913572423,Amara,62811
4,0065680265,እንዳግር በየነ አበራ,ENDAGER BEYENE ABERA,እንዳግር,በየነ,አበራ,0912394336,አማራ,ሰሜን ወሎ,ጋዞ,BOYA,አዲስ/New,0912394336,Amara,62221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2109,81592320,ሰይድ መሀመድ ያሲን,SAYDE MHAMED YASINE,ሰይድ,መሀመድ,ያሲን,0912755295,ቤኒሻንጉል ጉምዝ,አሶሳ,አሶሳ,GAMIBELA,አዲስ/New,0912756295,benshangul,64118
2110,270650997,ጌታ አለኸኝ ልመንህ,GATA ALEHEN LEMENHE,ጌታ,አለኸኝ,ልመንህ,0582440083,ቤኒሻንጉል ጉምዝ,አሶሳ,አሶሳ,KEBELE 04,አዲስ/New,0930076279,benshangul,71114
2111,270696412,መላኩ አቤ ባያብል,MELAKU ABEY BAYABELE,መላኩ,አቤ,ባያብል,0913451616,ቤኒሻንጉል ጉምዝ,አሶሳ,አሶሳ,KEBELE 02,አዲስ/New,0913451616,benshangul,71113
2112,270758355,ዳኜ አያና መንገሽ,DAGNE AYANA MANIGESHA,ዳኜ,አያና,መንገሽ,0911285895,ቤኒሻንጉል ጉምዝ,አሶሳ,ባምባሲ,KEBELE 02,አዲስ/New,0911285895,benshangul,61311
2113,430185503,አዝመራዉ ታደገ እንየው,AZIMRAW TADEG ENEYEW,አዝመራዉ,ታደገ,እንየው,0920246082,ቤኒሻንጉል ጉምዝ,አሶሳ,ባምባሲ,KEBELE 01,አዲስ/New,0920246082,benshangul,61311

In [6]:
masterdata=pd.merge(dataframe,category,left_on="Subgroupcode",right_on="category_id",how="left")

data=masterdata.drop_duplicates( keep='first', ignore_index=False)
data

,Tin,TradeNameAmh,EngilshName,ManagerFName,ManagerMName,ManagerLName,MangerPhone,BussinessAmharicRegions,BussinessAmharicZones,BussinessAmharicWoredas,BussinessAmharickebeles,HousNum,BussinessTelephone,Region,Subgroupcode,category_id,category_description
0,0061843031,መለሰ ሞገስ አለምነህ,MELESE MOGES ALEMINEH,መለሰ,ሞገስ,አለምነህ,0945141608,አማራ,ሰሜን ወሎ,ላስታ,DEBRE LOZA,አዲስ/New,0945141608,Amara,11121,11121.0,cattleand pack animals husbandery
1,0004291057,መለሰ ተፈራ ሁነኛው,MELSE TEFRA HUNEGNAW,መለሰ,ተፈራ,ሁነኛው,913477502,አማራ,ምዕራብ ጎጃም,ወንበርማ,KEBELE 01,አዲስ,0913477502,Amara,62221,62221.0,Retail trade in food products
2,0058448215,እየሩሳሌም ጌትነት ታደሰ,EYERUSALAME GETENATE TADAS,እየሩሳሌም,ጌትነት,ታደሰ,0912737194,አማራ,ሰሜን ሸዋ,ደብረ ብርሀን(ከተማ),KEBELE 06,0207/2,0912737194,Amara,62412,62412.0,"Retail trade of foot wear, leather and related..."
3,0044302998,ቀለም አያሌው ተሻለ,KELEM AYALEW TESHALE,ቀለም,አያሌው,ተሻለ,0913572423,አማራ,ምስራቅ ጎጃም,አነድድ,KEBELE 01,አዲስ/New,0913572423,Amara,62811,62811.0,Retail Trade Of Kerosin And Lubricants(without...
4,0065680265,እንዳግር በየነ አበራ,ENDAGER BEYENE ABERA,እንዳግር,በየነ,አበራ,0912394336,አማራ,ሰሜን ወሎ,ጋዞ,BOYA,አዲስ/New,0912394336,Amara,62221,62221.0,Retail trade in food products
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2529893,81592320,ሰይድ መሀመድ ያሲን,SAYDE MHAMED YASINE,ሰይድ,መሀመድ,ያሲን,0912755295,ቤኒሻንጉል ጉምዝ,አሶሳ,አሶሳ,GAMIBELA,አዲስ/New,0912756295,benshangul,64118,64118.0,Cafe and breakfast service
2529894,270650997,ጌታ አለኸኝ ልመንህ,GATA ALEHEN LEMENHE,ጌታ,አለኸኝ,ልመንህ,0582440083,ቤኒሻንጉል ጉምዝ,አሶሳ,አሶሳ,KEBELE 04,አዲስ/New,0930076279,benshangul,71114,71114.0,Transport service by road and dry freight
2529895,270696412,መላኩ አቤ ባያብል,MELAKU ABEY BAYABELE,መላኩ,አቤ,ባያብል,0913451616,ቤኒሻንጉል ጉምዝ,አሶሳ,አሶሳ,KEBELE 02,አዲስ/New,0913451616,benshangul,71113,71113.0,(71113)Land transport and related services
2529896,270758355,ዳኜ አያና መንገሽ,DAGNE AYANA MANIGESHA,ዳኜ,አያና,መንገሽ,0911285895,ቤኒሻንጉል ጉምዝ,አሶሳ,ባምባሲ,KEBELE 02,አዲስ/New,0911285895,benshangul,61311,61311.0,Wholesale trade in agricultural products (exce...
2529897,430185503,አዝመራዉ ታደገ እንየው,AZIMRAW TADEG ENEYEW,አዝመራዉ,ታደገ,እንየው,0920246082,ቤኒሻንጉል ጉምዝ,አሶሳ,ባምባሲ,KEBELE 01,አዲስ/New,0920246082,benshangul,61311,61311.0,Wholesale trade in agricultural products (exce...

In [7]:
data.to_csv(r"C:\Users\derek\OneDrive\Documents\Ethiopia Cleaned Data\addis_ababa_Cleaned_data.csv")